package com.example.roomdatabase

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

@Database([Contact::class], version = 2)    //"version 1" did not have Date in the schema
@TypeConverters(Converters::class)
//@AutoMigration()
abstract class ContactDatabase : RoomDatabase() {

    //The body of this method is generated by Room in ContactDatabase_Impl (We don't write the implementation here)
    abstract fun contactDao(): ContactDAO

    //Implementing singleton pattern for database instance, because there should be only one database instance in one application
    companion object {

        private val migration_1_2 = object : Migration(1, 2) {     //Migration is an abstract class, so we create its object(grand child) through anonymous object
            override fun migrate(db: SupportSQLiteDatabase) {   //previously this migrate function was an abstract function, but now this is an open function
                db.execSQL("ALTER TABLE contact ADD COLUMN isActive INTEGER NOT NULL DEFAULT(1)")   //order of new column will be decide according to data class. Even if here, isActive is added before createdDate, still isActive will be shown after createdDate in the database table.
                db.execSQL("ALTER TABLE contact ADD COLUMN createdDate INTEGER")                    //order of new column is not decided by this sql query executions.
                //super.migrate(db)       //if nothing will be done here, then this will throw NotImplementedError
            }
        }

        @Volatile   //As soon as INSTANCE value will change, this will send the current value to all the active threads (Marks the JVM backing field of the annotated var property as volatile)
        private var INSTANCE: ContactDatabase? = null

        fun getDatabase(context: Context): ContactDatabase {
            //There is still a possibility that two different threads try access the database instance at the same time.
            // So, for that,here synchronized method is used.
            synchronized(this) {        //Executes the given function block while holding the monitor of the given object lock.
                if (INSTANCE == null) {
                    INSTANCE = Room.databaseBuilder(context.applicationContext,
                        ContactDatabase::class.java,
                        "contactDB")
                        .addMigrations(migration_1_2)
                        .build()
                }
                return INSTANCE!!

            }
        }
    }
}